# Generated by Django 4.1 on 2022-08-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("num2", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
