# Generated by Django 4.1 on 2022-08-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("num2", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(name="FieldValues",),
    ]
