# Generated by Django 4.1 on 2022-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0002_post_delete_fieldvalues"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="add",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="neg",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="square",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
