# Generated by Django 4.1.1 on 2022-09-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0012_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="Currency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="data",
            name="Product",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
