# Generated by Django 4.1.1 on 2022-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0013_data_currency_data_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="Currency",
            field=models.CharField(default="Rupee", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="data",
            name="Name",
            field=models.CharField(default="x", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="data",
            name="Product",
            field=models.CharField(default="Onions", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="data",
            name="Region",
            field=models.CharField(
                choices=[("A", "a"), ("B", "b")], default="y", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="data",
            name="Selection",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
