# Generated by Django 4.1.1 on 2022-09-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("table", "0015_data_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
        ),
    ]
